source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem "rake", ">= 12.3.3"
gem "rack", ">= 2.0.8"
gem 'rails', '~> 5.2.3'
gem 'pg', '>= 0.18', '< 2.0'
gem "puma", ">= 3.12.4"
gem 'bootsnap', '>= 1.1.0', require: false
gem 'jbuilder', '~> 2.5'

group :development, :test do
  gem 'faker'
  gem 'rspec-rails'
  gem 'pry-nav'
  gem 'pry-rails'
  gem 'pry-rescue'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'json_matchers'
  gem 'rspec-collection_matchers'
  gem 'shoulda-matchers', '~> 3.0'
  gem 'simplecov', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
